// Single source of truth for project metadata.
// Image data comes from /images/projects/proj-XX/manifest.json.

export const PROJECTS = [
  {
    id: '01',
    slug: '1',
    title: '산운12단지 판교센트럴포레와이시티',
    subtitle: '판교 24평, 욕실 두 곳까지 손본 풀 리모델링',
    apartment: '산운12단지 판교센트럴포레와이시티 아파트',
    address: '성남시 분당구 판교동',
    pyeong: '24평',
    period: '4주',
    completedAt: '2026년 3월',
    type: 'apartment',
    pricePerPy: '평당 360~410만 원대',
    keywords: '판교 24평, 욕실 두 곳, 정갈한 라인',
    scope: '거실, 주방, 욕실 2곳, 침실 3곳, 현관',
    description: [
      '컴팩트한 24평이지만 거실·주방·욕실 두 곳·침실 세 곳·현관까지 한 번에 손본 풀 리모델링이에요.',
      '톤은 차분하게 유지하면서, 마감재 디테일에 변화를 줘서 좁은 공간에서도 답답하지 않게 정리했습니다.',
      '욕실 A·B의 비포·에프터를 비교해보면 같은 톤 안에서 어떻게 다른 분위기를 만들었는지 한눈에 들어옵니다.',
    ],
    sectionLabels: {
      living: '거실',
      kitchen: '주방',
      'bath-a': '욕실-A',
      'bath-b': '욕실-B',
      'bed-a': '침실-A',
      'bed-b': '침실-B',
      'bed-c': '침실-C',
      entrance: '현관',
    },
  },
  {
    id: '02',
    slug: '2',
    title: '성복역 롯데캐슬골드타운',
    subtitle: '따뜻한 우드톤으로 마무리한 35평 아파트',
    apartment: '성복역 롯데캐슬골드타운 아파트',
    address: '용인시 수지구 성복동',
    pyeong: '35평',
    period: '4주',
    completedAt: '2025년 9월',
    type: 'apartment',
    pricePerPy: '평당 350~400만 원대',
    keywords: '따뜻한 우드, 정돈된 동선, 35평 아파트',
    scope: '거실, 주방, 침실, 현관',
    description: [
      '거실과 주방 동선을 깔끔하게 정리하고, 우드 톤 마감재로 따뜻한 분위기를 살렸어요.',
      '세 곳의 침실은 각각의 용도에 맞춰 수납과 조명 계획을 다르게 가져갔습니다.',
      '현관은 신발장과 간살도어를 함께 시공해 외부 시선이 분산되도록 설계했어요.',
    ],
    sectionLabels: {
      living: '거실',
      kitchen: '주방',
      'bed-a': '침실-A',
      'bed-b': '침실-B',
      'bed-c': '침실-C',
      entrance: '현관',
    },
  },
  {
    id: '03',
    slug: '3',
    title: '신당동 남산타운',
    subtitle: '컴팩트한 26평을 효율적으로 풀어낸 리모델링',
    apartment: '남산타운 아파트',
    address: '서울시 중구 신당동',
    pyeong: '26평',
    period: '3주',
    completedAt: '2024년 10월',
    type: 'apartment',
    pricePerPy: '평당 300~340만 원대',
    keywords: '소형 평형, 수납 극대화, 차분한 무드',
    scope: '거실, 안방, 현관',
    description: [
      '좁은 동선을 시원하게 풀어내면서도 수납을 충분히 확보하는 데에 집중했어요.',
      '거실은 빌트인 가구와 매립등으로 정돈된 라인을 만들었고, 안방은 화이트 톤으로 차분하게 정리했습니다.',
      '현관의 비포·에프터를 비교해보면 톤과 마감재 차이가 가장 또렷하게 보입니다.',
    ],
    sectionLabels: {
      living: '거실',
      bedroom: '안방',
      entrance: '현관',
    },
  },
  {
    id: '04',
    slug: '4',
    title: '은어송마을 코오롱하늘채2단지',
    subtitle: '대전 35평, 가족이 머무는 자리를 정리하다',
    apartment: '은어송마을 코오롱하늘채2단지 아파트',
    address: '대전 동구 대성동',
    pyeong: '35평',
    period: '4주',
    completedAt: '2025년 7월',
    type: 'apartment',
    pricePerPy: '평당 320~380만 원대',
    keywords: '가족형 아파트, 밝은 화이트, 우드 포인트',
    scope: '거실, 주방, 침실, 현관',
    description: [
      '거실과 주방을 부드럽게 연결하면서, 식사·휴식·작업 영역을 한 시야에서 보이도록 정리했어요.',
      '세 침실은 가족 구성원의 사용 시간대를 고려해 조명과 마감의 톤을 다르게 가져갔습니다.',
      '현관은 비포·에프터의 차이가 가장 크게 느껴지는 공간 중 하나입니다.',
    ],
    sectionLabels: {
      living: '거실',
      kitchen: '주방',
      'bed-a': '침실-A',
      'bed-b': '침실-B',
      'bed-c': '침실-C',
      entrance: '현관',
    },
  },
  {
    id: '05',
    slug: '5',
    title: '이태원 단독주택 에어비엔비',
    subtitle: '게스트의 동선을 고려한 34평 단독주택 리모델링',
    apartment: '이태원 단독주택',
    address: '서울시 용산구 보광동',
    pyeong: '34평',
    period: '4주',
    completedAt: '2025년 2월',
    type: 'house',
    pricePerPy: '평당 380~430만 원대',
    keywords: '에어비엔비, 게스트 동선, 단독주택',
    scope: '거실, 주방, 객실 3개',
    description: [
      '게스트가 짧게 머무는 공간이라는 점을 고려해, 사진을 찍었을 때 가장 좋아 보이는 시점을 우선했어요.',
      '거실과 주방은 오픈 구조로 풀고, 세 객실은 각각 다른 컨셉으로 꾸며 머무는 즐거움을 다르게 줬습니다.',
      '거실의 비포·에프터를 비교하면 가구 배치와 톤이 어떻게 달라졌는지 한눈에 들어옵니다.',
    ],
    sectionLabels: {
      living: '거실',
      kitchen: '주방',
      'room-a': 'Room-A',
      'room-b': 'Room-B',
      'room-c': 'Room-C',
    },
  },
  {
    id: '06',
    slug: '6',
    title: '판교원9단지 한림풀에버',
    subtitle: '판교 29평, 모든 공간을 손본 풀 리모델링',
    apartment: '판교원9단지 한림풀에버 아파트',
    address: '성남시 분당구 판교동',
    pyeong: '29평',
    period: '5주',
    completedAt: '2025년 10월',
    type: 'apartment',
    pricePerPy: '평당 380~420만 원대',
    keywords: '풀 리모델링, 욕실 두 곳, 정갈한 라인',
    scope: '거실, 주방, 욕실 2곳, 침실 3곳, 현관',
    description: [
      '거실·주방·욕실 두 곳·침실 세 곳·현관까지, 집의 모든 공간을 한 번에 손본 풀 리모델링이에요.',
      '톤은 차분하게 유지하면서도 마감재 디테일에 변화를 줘서 공간마다 표정이 다르게 느껴지도록 했습니다.',
      '욕실 A·B 두 곳의 비포·에프터를 비교하면 같은 톤 안에서 어떻게 다른 분위기를 만들었는지 볼 수 있어요.',
    ],
    sectionLabels: {
      living: '거실',
      kitchen: '주방',
      'bath-a': '욕실-A',
      'bath-b': '욕실-B',
      'bed-a': '침실-A',
      'bed-b': '침실-B',
      'bed-c': '침실-C',
      entrance: '현관',
    },
  },
];

export const PROJECTS_BY_ID = Object.fromEntries(PROJECTS.map((p) => [p.id, p]));
